package transport

import (
	"crypto/tls"
	"net"
	"testing"
	"time"
)

// This is a bug condition EXPLORATION test for Bug 5 — the QUIC transport
// authenticates nothing. The shared-secret-derived certificate is generated by
// tlsConfigFromSecret but never verified: the client sets InsecureSkipVerify
// with no VerifyPeerCertificate, and the server requests no client cert. As a
// result a handshake between peers configured with DIFFERENT shared secrets
// still completes.
//
// The authentication outcome is entirely determined by the *tls.Config values
// produced by tlsConfigFromSecret, so we can exercise the real behavior with a
// standard crypto/tls 1.3 handshake over net.Pipe — pure Go, no pcap/QUIC/CGO.
//
// This test encodes the EXPECTED (correct) behavior and therefore MUST FAIL on
// the current unfixed code. A failure here confirms Bug 5 exists.

// tlsHandshake drives a TLS 1.3 handshake between a server config and a client
// config over an in-memory pipe, returning the client-side and server-side
// handshake errors. A deadline guards against a stalled handshake hanging the
// test.
func tlsHandshake(t *testing.T, serverCfg, clientCfg *tls.Config) (clientErr, serverErr error) {
	t.Helper()

	cp, sp := net.Pipe()
	deadline := time.Now().Add(5 * time.Second)
	_ = cp.SetDeadline(deadline)
	_ = sp.SetDeadline(deadline)
	defer cp.Close()
	defer sp.Close()

	done := make(chan error, 1)
	go func() {
		s := tls.Server(sp, serverCfg)
		defer s.Close()
		done <- s.Handshake()
	}()

	c := tls.Client(cp, clientCfg)
	defer c.Close()
	clientErr = c.Handshake()
	serverErr = <-done
	return
}

// Bug 5 — Property 5: a QUIC handshake whose peer certificate is not derived
// from the local shared secret MUST be rejected. Here the server is configured
// from "secretA" and the client from "secretB" (a DIFFERENT secret), so the
// certificates do not match and the handshake must fail on at least one side.
//
// On the UNFIXED code the handshake SUCCEEDS (both sides return nil) because the
// client skips verification and the server requires no client cert — so this
// assertion FAILS, confirming Bug 5.
//
// **Validates: Requirements 1.6, 1.7**
func TestQUICAuth_MismatchedSecret_BugCondition(t *testing.T) {
	serverCfg, err := tlsConfigFromSecret("secretA", "paqetpremium", true)
	if err != nil {
		t.Fatalf("building server TLS config: %v", err)
	}
	clientCfg, err := tlsConfigFromSecret("secretB", "paqetpremium", false)
	if err != nil {
		t.Fatalf("building client TLS config: %v", err)
	}

	clientErr, serverErr := tlsHandshake(t, serverCfg, clientCfg)

	// Expected (correct, post-fix) behavior: the mismatched-secret handshake is
	// rejected, so at least one side returns a non-nil error.
	if clientErr == nil && serverErr == nil {
		t.Fatalf("Bug 5 reproduced: mismatched-secret handshake completed with no error "+
			"(clientErr=%v, serverErr=%v); expected the handshake to be rejected because the "+
			"peer certificate is not derived from the local shared secret", clientErr, serverErr)
	}
}
